services:
  - type: web
    name: smart-hospital
    env: docker
    plan: starter
    region: oregon
    dockerfilePath: ./Dockerfile
    disk:
      name: smart-hospital-uploads
      mountPath: /var/www/html/uploads
      sizeGB: 1
    envVars:
      - key: DB_HOST
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASS
        sync: false
      - key: DB_NAME
        sync: false
      - key: DB_PORT
        value: "3306"
      - key: BASE_URL
        sync: false
