<style>
    .qr-workspace{max-width:1240px;margin:0 auto;color:#34465e}.qr-hero{padding:25px 28px;background:linear-gradient(115deg,#073b5b,#087f85);border-radius:10px 10px 0 0;color:#fff}.qr-hero h3{margin:0 0 5px;font-size:23px;font-weight:700}.qr-hero p{margin:0;color:rgba(255,255,255,.8)}.qr-hero .btn{background:#fff;color:#087f85;border:0;font-weight:600}.qr-shell{border:1px solid #dfe8ee;border-top:0;border-radius:0 0 10px 10px;background:#fff;padding:25px;box-shadow:0 3px 12px rgba(33,58,78,.07)}
    .qr-tabs{display:flex;gap:9px;border:0;margin:0 0 24px}.qr-tabs li{float:none;margin:0}.qr-tabs .nav-link{margin:0;border:1px solid #d9e4ea!important;border-radius:6px!important;color:#5a7089;font-weight:600;padding:10px 16px}.qr-tabs .nav-link.active,.qr-tabs .nav-link:hover{background:#e5f8f7!important;border-color:#00aaa7!important;color:#007e7d!important}.qr-panel{border:1px solid #e4edf2;border-radius:8px;padding:25px;min-height:350px}.qr-section-label{color:#008f8d;font-size:12px;letter-spacing:.7px;font-weight:700;margin-bottom:12px}.qr-scan-title{font-size:21px;font-weight:700;color:#233951;margin:0 0 8px}.qr-scan-subtitle{color:#7589a0;margin-bottom:20px}.qr-input-wrap{position:relative}.qr-input-wrap i{position:absolute;left:18px;top:17px;color:#00aaa7;font-size:19px}.qr-input-wrap input{height:58px;border:2px solid #00aaa7;border-radius:7px;padding-left:52px;font-size:18px;box-shadow:0 0 0 4px rgba(0,170,167,.1)}.qr-input-wrap input:focus{box-shadow:0 0 0 4px rgba(0,170,167,.16)}.qr-tip{display:flex;gap:12px;margin-top:21px;color:#617890;line-height:1.5}.qr-tip i{color:#00aaa7;background:#e7f8f7;border-radius:6px;padding:9px;height:35px}.qr-tip strong{color:#34465e}.qr-status-panel{background:#f8fbfc;border:1px solid #e4edf2;border-radius:8px;min-height:350px;padding:26px}.qr-empty{text-align:center;padding-top:62px;color:#8294aa}.qr-empty .qr-symbol{font-size:52px;color:#c5d3df;margin-bottom:14px}.qr-empty h4{color:#34465e;font-weight:700}.qr-result-card{padding:5px}.qr-person-icon{width:54px;height:54px;border-radius:50%;background:#dff7f3;color:#008e88;text-align:center;padding-top:15px;font-size:23px;float:left;margin-right:14px}.qr-person-name{font-size:20px;font-weight:700;color:#203951}.qr-person-meta{color:#71869c;margin-top:3px}.qr-result-alert{clear:both;margin-top:25px;border-radius:7px;padding:15px 17px}.qr-camera{min-height:270px;background:#102e44;border-radius:8px;overflow:hidden;position:relative}.qr-camera video{width:100%;height:310px;object-fit:cover;display:none}.qr-camera #html5-reader{display:none;height:310px}.qr-camera #html5-reader video{display:block!important;height:310px!important;object-fit:cover}.qr-guide{position:absolute;inset:20% 30%;border:3px solid #00c3bd;border-radius:12px;pointer-events:none}.qr-camera-help{padding:90px 30px;color:#fff;text-align:center}.qr-camera-help i{font-size:42px;color:#3dd5cb;display:block;margin-bottom:15px}@media(max-width:991px){.qr-status-panel{margin-top:20px}.qr-hero{padding:20px}.qr-shell{padding:16px}}
</style>
<div class="row"><div class="col-md-12"><div class="qr-workspace">
    <div class="qr-hero clearfix"><a class="btn btn-sm pull-right" href="<?php echo site_url('admin/qrattendance/setting/index'); ?>"><i class="fa fa-cog"></i> Settings</a><h3><i class="fa fa-qrcode"></i> QR Code Attendance</h3><p>Scan a staff ID card to automatically record check-in or check-out.</p></div>
    <div class="qr-shell"><input type="hidden" id="qr-csrf" name="<?php echo $this->security->get_csrf_token_name(); ?>" value="<?php echo $this->security->get_csrf_hash(); ?>">
        <ul class="nav nav-tabs qr-tabs"><li class="nav-item"><a class="nav-link active" href="#scanner" data-bs-toggle="tab"><i class="fa fa-barcode"></i> Sensor-based device</a></li><?php if ($settings['camera_enabled']) { ?><li class="nav-item"><a class="nav-link" href="#camera" data-bs-toggle="tab"><i class="fa fa-camera"></i> Camera-based device</a></li><?php } ?></ul>
        <div class="tab-content"><div class="tab-pane active" id="scanner"><div class="row"><div class="col-md-7"><div class="qr-panel"><div class="qr-section-label"><i class="fa fa-circle"></i> READY TO SCAN</div><h4 class="qr-scan-title">Scan your staff ID card</h4><div class="qr-scan-subtitle">Use a barcode scanner, or type the employee ID and press Enter.</div><div class="qr-input-wrap"><i class="fa fa-barcode"></i><input id="scan-code" class="form-control" autocomplete="off" autofocus placeholder="Scan your ID card QR code / barcode" <?php echo !$settings['scanner_enabled'] ? 'disabled' : ''; ?>></div><div class="qr-tip"><i class="fa fa-keyboard-o"></i><div><strong>Scanner ready</strong><br>Scanner guns act like keyboards. This field stays ready for the next scan.</div></div><div class="qr-tip"><i class="fa fa-clock-o"></i><div><strong>Automatic in / out</strong><br>First scan checks in; the next scan checks out.</div></div></div></div><div class="col-md-5"><div id="scan-result" class="qr-status-panel"><div class="qr-empty"><div class="qr-symbol"><i class="fa fa-qrcode"></i></div><h4>Waiting for a scan</h4><p>Staff details and attendance status will appear here.</p></div></div></div></div></div>
        <?php if ($settings['camera_enabled']) { ?><div class="tab-pane" id="camera"><div class="row"><div class="col-md-7"><div class="qr-panel"><div class="qr-section-label"><i class="fa fa-circle"></i> CAMERA SCANNER</div><div class="qr-camera"><video id="camera-video" playsinline></video><div id="html5-reader"></div><div class="qr-guide"></div><div id="camera-help" class="qr-camera-help"><i class="fa fa-camera"></i>Start the camera and hold the QR code in the highlighted area.</div></div><button type="button" id="start-camera" class="btn btn-primary mt-3"><i class="fa fa-camera"></i> Start camera</button><p class="text-muted mt-2 mb-0">Camera scanning needs HTTPS and browser permission.</p></div></div><div class="col-md-5"><div id="camera-result" class="qr-status-panel"><div class="qr-empty"><div class="qr-symbol"><i class="fa fa-mobile"></i></div><h4>Camera not started</h4><p>Use your device camera to scan a QR code.</p></div></div></div></div></div><?php } ?></div>
    </div>
</div></div></div>
<?php if ($settings['camera_enabled']) { ?><script src="<?php echo base_url('backend/qrattendance/html5-qrcode.min.js'); ?>"></script><?php } ?>
<script>
(function(){
    var input=document.getElementById('scan-code'), status=document.getElementById('scan-result'), cameraStatus=document.getElementById('camera-result'), busy=false, stream=null, html5Scanner=null;
    function escapeHtml(value){var e=document.createElement('div');e.textContent=value||'';return e.innerHTML;}
    function renderCameraReady(){if(!cameraStatus)return;cameraStatus.innerHTML='<div class="qr-empty"><div class="qr-symbol" style="color:#00a99d"><i class="fa fa-camera"></i></div><h4>Camera ready</h4><p><span class="label label-success"><i class="fa fa-circle"></i> SCANNING ACTIVE</span></p><p>Hold the staff QR code inside the scan frame.</p></div>';}
    function render(data,target){target=target||status;var staff=data.staff||{}, good=Number(data.status)===1, warning=Number(data.status)===2, type=good?'success':(warning?'warning':'danger');if(!staff.name){target.innerHTML='<div class="qr-empty"><div class="qr-symbol"><i class="fa fa-exclamation-circle"></i></div><h4>'+escapeHtml(data.message||'Scan could not be completed')+'</h4><p>Please check the staff card and try again.</p></div>';return;}target.innerHTML='<div class="qr-result-card"><div class="qr-person-icon"><i class="fa fa-user"></i></div><div class="qr-person-name">'+escapeHtml(staff.name+' '+(staff.surname||''))+'</div><div class="qr-person-meta">'+escapeHtml(staff.employee_id||'')+(staff.role_name?' &middot; '+escapeHtml(staff.role_name):'')+'</div><div class="alert alert-'+type+' qr-result-alert"><strong><i class="fa fa-'+(good?'check-circle':'exclamation-circle')+'"></i> '+escapeHtml(data.message||'')+'</strong>'+(data.attendance?'<br><small>In: '+escapeHtml(data.attendance.in_time||'—')+' &nbsp; | &nbsp; Out: '+escapeHtml(data.attendance.out_time||'—')+'</small>':'')+'</div></div>';}
    function submit(code,target){if(!code||busy)return;busy=true;var csrf=document.getElementById('qr-csrf'),payload={code:code};payload[csrf.name]=csrf.value;$.ajax({url:'<?php echo site_url('admin/qrattendance/attendance/scan'); ?>',type:'POST',data:payload,dataType:'json'}).done(function(data){if(data.csrf_hash){csrf.value=data.csrf_hash;}render(data,target);}).fail(function(xhr){var response=xhr.responseJSON;if(!response&&xhr.responseText){try{response=JSON.parse(xhr.responseText);}catch(e){}}render(response||{status:0,message:'Attendance request failed (HTTP '+xhr.status+'). Check the server error log.'},target);}).always(function(){busy=false;if(input){input.value='';input.focus();}});}
    if(input){input.addEventListener('keydown',function(event){if(event.key==='Enter'){event.preventDefault();submit(input.value.trim());}});}
    var button=document.getElementById('start-camera');if(button){button.addEventListener('click',function(){if(!window.isSecureContext){return render({status:0,message:'Camera access requires HTTPS. Open this hospital URL using https:// and try again.'},cameraStatus);}if(!navigator.mediaDevices||!navigator.mediaDevices.getUserMedia){return render({status:0,message:'Camera access is not supported by this browser. Use current Chrome or Edge.'},cameraStatus);}if(!('BarcodeDetector' in window)&&window.Html5Qrcode){return startHtml5Decoder();}navigator.mediaDevices.getUserMedia({video:{facingMode:'<?php echo $settings['camera_facing_mode']; ?>'}}).then(function(s){stream=s;var video=document.getElementById('camera-video');video.srcObject=s;video.style.display='block';video.play();document.getElementById('camera-help').style.display='none';button.disabled=true;button.innerHTML='<i class="fa fa-check"></i> Camera started';renderCameraReady();if('BarcodeDetector' in window){detect(video);}else{startHtml5Decoder();}}).catch(cameraError);});}
    function startHtml5Decoder(){var reader=document.getElementById('html5-reader');if(!reader||!window.Html5Qrcode){return render({status:0,message:'QR decoder could not be loaded. Please refresh the page and try again.'},cameraStatus);}document.getElementById('camera-help').style.display='none';document.querySelector('.qr-guide').style.display='none';reader.style.display='block';html5Scanner=new Html5Qrcode('html5-reader');html5Scanner.start({facingMode:'<?php echo $settings['camera_facing_mode']; ?>'},{fps:10,qrbox:{width:250,height:250},aspectRatio:1.5},function(decodedText){submit(decodedText,cameraStatus);},function(){}).then(function(){button.disabled=true;button.innerHTML='<i class="fa fa-check"></i> Camera started';renderCameraReady();}).catch(cameraError);}
    function cameraError(error){var message=error&&error.name==='NotAllowedError'?'Camera permission was blocked. Click the camera icon in the browser address bar and allow access.':(error&&error.name==='NotFoundError'?'No camera device was found. Connect a webcam and try again.':'Unable to start the camera. Please close other apps using it and try again.');render({status:0,message:message},cameraStatus);}
    function detect(video){var detector;try{detector=new BarcodeDetector({formats:['qr_code','code_128','ean_13']});}catch(e){render({status:2,message:'Camera is ready. Use the barcode input if QR detection is unavailable.'},cameraStatus);return;}(function loop(){if(!stream)return;detector.detect(video).then(function(codes){if(codes.length)submit(codes[0].rawValue,cameraStatus);}).catch(function(){}).then(function(){setTimeout(loop,500);});})();}
    window.addEventListener('beforeunload',function(){if(stream)stream.getTracks().forEach(function(track){track.stop();});if(html5Scanner)html5Scanner.stop().catch(function(){});});
})();
</script>
